# 開発環境用Dockerfile
FROM node:22-alpine

# 作業ディレクトリを設定
WORKDIR /app

# パッケージファイルをコピー
COPY ./package.json ./yarn.lock* ./package-lock.json* ./pnpm-lock.yaml* ./

# 依存関係をインストール
RUN \
  if [ -f yarn.lock ]; then yarn install; \
  elif [ -f package-lock.json ]; then npm install; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm install; \
  else echo "Lockfile not found." && exit 1; \
  fi

# アプリケーションコードをコピー
COPY . .

# ポートを公開
EXPOSE 3000

# 開発サーバーを起動
CMD ["yarn", "dev"]
